version: "2.0"


services:
  Goauth:
    image: ugurozsahin/go-auth:v2
    ports:
      - "9000:9000"
    command:
      - "-l"
      - "debug"
      - "run"
      - "--db-host"
      - "db"
      - "-p"
      - "9000"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: messenger
      MYSQL_USER: messenger
      MYSQL_PASSWORD: messenger