FROM scratch

MAINTAINER ugurozsahin@live.com

#RUN mkdir -p /etc/ssl/certs
#ADD /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD ./go-auth /bin/go-auth

EXPOSE 9000

ADD run-go-auth.sh /bin/start-go-auth.sh

ENTRYPOINT ["/bin/start-go-auth.sh"]